### ISSUE TITLE
Input values become zeros on iOS 11 with WebGPU

### ISSUE THREAD

**Issue by Aixile** [mil-tokyo/webdnn#566]
**Ref https://github.com/makegirlsmoe/makegirls.moe_web/issues/25**

I try to run our site with iPhone 7 / iOS 11, but the output results stay the same no matter what the input is.

![](https://i.imgur.com/8X3oe4K.jpg)

After some investigation, I find that the image can be generated by a 162-dim zero vector, so the actual input is always zero.

Moreover, I attempt to log the value of `staticBuffer.bufferView[4*4422659]`
(According to [graph_webgpu.json](https://github.com/makegirlsmoe/makegirls.moe_web/blob/master/public/models/Amaryllis_8bit/graph_webgpu.json) , the input are stored in position 4422659), but it seems that this value varies every time.

There is no such issue on macOS's safari 11 and safari TP, thus I suspect it's an iOS system bug.

**Comment by milhidaka** [comment]
Thank you for reporting.
The problem is caused by thread group setting of WebGPU kernel, and I think it is resolved at commit 9c859f1e.
Please install latest webdnn and try to convert your model again.
The value of this line will change.
https://github.com/makegirlsmoe/makegirls.moe_web/blob/master/public/models/Amaryllis_8bit/graph_webgpu.json#L3794

**Comment by Aixile** [comment]
I rebuild the model and the problem is solved!
Thanks!
