### ISSUE TITLE
convert Lambda

### ISSUE THREAD

**Issue by nikhilaravi** [mil-tokyo/webdnn#598]
I'm trying to convert the [yolo_v2 model](https://github.com/allanzelener/YAD2K/blob/master/test_yolo.py) to webdnn but ran into an error with a Lambda layer - it seems the '_convert_lambda' function has not yet been implemented: 
```
@KerasConverter.register_handler("Lambda")
def _convert_lambda(converter: KerasConverter, k_op: "keras.layers.Lambda"):
    # TODO
    raise NotImplementedError('[KerasConverter] keras.layers.Lambda is not supported')
```

Would you be able to implement this or suggest how we can implement it ourselves?

We're working on a project to showcase NN with JS using WedDNN for NodeConf Argentina on October 26th so would greatly appreciate a speedy response!

**Comment by Ninh** [comment]
Is there a timeline for when this would be implemented?

**Comment by Kiikurage** [comment]
We don't have the plan to support lambda layer, because it's very difficult.
However, `KerasConverter` try to convert a model by using `TensorFlowConverter` first, and
 if it failed, use `KerasConverter`. Therefore, if follow conditions are satisfied, model including lambda layer can be converted.

1. All operations in Keras' lambda layer are implemented through TensorFlow function like `K.add()`.
2. All corresponding TensorFlow operators (ex. `tf.add()` for `K.add()`) are supported in WebDNN's `TensorFlowConverter`.

If error message like `[KerasConverter] keras.layers.Lambda is not supported` is displayed, it means,
1. TensorFlowConverter failed to convert your model because of some error.
2. KerasConverter cannot convert your model because lambda layer is not supported.

By setting the environment variable DEBUG = 1 and executing KerasConverter again, you can check the reason why conversion of TensorFlowConverter failed.

**Comment by Ninh** [comment]
Thank you for your prompt response. I tried to convert the model using TensorFlowConverter and it looks like there's another function that isn't implemented yet:

`raise NotImplementedError(f"[TensorFlowConverter] {tf_op.type} is not supported yet.")
NotImplementedError: [TensorFlowConverter] Placeholder is not supported yet.`

What would you recommend I do?

**Comment by Kiikurage** [comment]
Maybe some input (=tf.placeholder) tensor is not specified.

```
import tensorflow as tf
from webdnn.frontend.tensorflow import TensorFlowConverter

x = tf.placeholder(tf.float32, [None, 10])
y = tf.placeholder(tf.float32, [None, 10])
z = x + y

# Because tensor "y" is not specified as input tensor, "Placeholder is not supported" error will be occurred.
TensorFlowConverter(tf.get_default_session()).convert([x], [z])
```

**Comment by Ninh** [comment]
Hi, my friend tried running TensorFlowConverter with his GPUs and he is getting this error that seems to be for Caffe models (from a cursory google search).

`AttributeError: 'google.protobuf.pyext._message.RepeatedScalarConta' object has no attribute '_values'`

**Comment by Kiikurage** [comment]
Sorry, I told wrong things. In current master branch, `KerasConverter` doesn't use `TensorFlowConverter` in conversion yet.

> `AttributeError: 'google.protobuf.pyext._message.RepeatedScalarConta' object has no attribute '_values'`

Maybe it's caused by different problem. I create another issue #624 to discuss that problem.
