### ISSUE TITLE
cannot converting "h5" into computation graph format

### ISSUE THREAD

**Issue by akshay951228** [mil-tokyo/webdnn#717]
![wednn](https://user-images.githubusercontent.com/25878082/34483502-e0d709f8-efe4-11e7-872f-4287da2d828c.png)
raise NotImplementedError(f"[{cls.__name__}] Operator {op} is not handled by any generator handler")
NotImplementedError: [FallbackDescriptorGenerator] Operator <Im2Col inputs={'im': <Variable Variable11 shape=(1, 60, 60, 8), order=[N, H, W, C]>}, outputs={'col': <Variable Variable13 shape=(1, 60, 60, 3, 3, 8), order=[N, H, W, KH, KW, C]>}> is not handled by any generator handler

**Comment by Kiikurage** [comment]
This is because FallbackDescriptorGenerator doesn't support Im2Col operator.  Each WebDNN computing backend doesn't supports all operators.

BTW, Im2Col operator in WebDNN is not used in fallback backend, and this error is not occured in general.  I wonder why Im2Col operator is passed to FallbackDescriptorGenerator.
If possible, can you tell me how to reproduce this problem?

**Comment by akshay951228** [comment]
in this github repo ## https://github.com/JustinShenk/party-pi  you can find a this file **emotion_model.hdf5**.download this file an convert in webdnn graph then you will get same error.
