### ISSUE TITLE
No axis is splittable Error on generating descriptor for webgl from chainer facenet

### ISSUE THREAD

**Issue by seranus** [mil-tokyo/webdnn#829]
Hey, I'm trying to convert the Chainer model from https://github.com/DeNA/Chainer_Realtime_Multi-Person_Pose_Estimation

Specifically https://github.com/DeNA/Chainer_Realtime_Multi-Person_Pose_Estimation/blob/master/face_detector.py

And I'm getting No axis is splittable only on webgl others seem to work without errors

webdnn\backend\webgl\optimize_rules\split_texture\split_variable.py:208 in _choose_split_axis
webdnn\backend\webgl\optimize_rules\split_texture\split_variable.py:49 in SplitVariable.optimize
webdnn\graph\optimize_rule.py:110 in OptimizeRuleGroup.optimize
webdnn\graph\optimize_rule.py:110 in OptimizeRuleGroup.optimize
webdnn\graph\optimize_rule.py:110 in OptimizeRuleGroup.optimize
webdnn\backend\webgl\generator.py:45 in WebGLDescriptorGenerator.generate
webdnn\backend\webgl\generator.py:92 in generate
webdnn\backend\interface\generator.py:107 in generate_descriptor
Chainer_Realtime_Multi-Person_Pose_Estimation-master\face_detector.py:45 in FaceDetector.__call__

**Comment by Kiikurage** [comment]
In WebGL backend, maximum tensor size is depend on device supported texture size. When your model uses tensors which are larger than these limitation, WebDNN automatically try to split these tensors to smaller sub-tensors. However, this splitting can NOT be performed for all operators. In your case, your model uses large tensor, but WebDNN cannot split it because WebDNN don't know how to split some operators corresponding to the large tensor.

**Comment by seranus** [comment]
Thanks for the fast replay
